name: Original with Ext Env

on:
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: Environment
        type: choice
        options:
          - a
          - b

jobs:
  MAIN: 
   runs-on: ubuntu-latest
   steps:
      - id: CHECKOUT
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - id: ENV
        run: |
          for s in $(cat "envs/${{ github.event.inputs.environment }}.json" | jq -r "to_entries|map(\"ENV_\(.key|ascii_upcase)=\(.value|tostring)\")|.[]" ); do
            echo $s >> $GITHUB_ENV
          done

      - id: ECHO
        run: |
          cat <<- EOM
          {
            "environment: [{
               "name": "HARDCODED_VARIABLE",
               "value": "hardcoded"
            }, {
               "name": "SOME_VARIABLE",
               "value": "$ENV_SOME_VARIABLE"
            }, {
               "name": "ANOTHER_VARIABLE",
               "value": "$ENV_ANOTHER_VARIABLE"
            }]
          }
          EOM
          
