name: Reuse - Ext

on:
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: Environment
        type: choice
        options:
          - a
          - b

jobs:
  INPUT: 
   runs-on: ubuntu-latest
   steps:
      - id: CHECKOUT
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - id: ENV
        run: |
          if [[ -z "${{ github.event.inputs.environment }}" ]]; then
            INPUT=$(jq -n 'inputs' envs/*.json)
          else
            INPUT=[$(cat envs/${{ github.event.inputs.environment }}.json)]
          fi
          echo $INPUT
          echo "::set-output name=INPUT_JSON::$INPUT"
   outputs: 
    INPUT_JSON: ${{ steps.ENV.outputs.INPUT_JSON }}

  MAIN: 
   uses: ./.github/workflows/reuse-json-input.yml
   needs: INPUT
   with:
    INPUT_JSON: ${{ needs.INPUT.outputs.INPUT_JSON }} 
