name: Reuse - Ext

on:
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: Environment
        type: choice
        options:
          - a
          - b

jobs:
  INPUT: 
   runs-on: ubuntu-latest
   steps:
      - id: CHECKOUT
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - id: ENV
        run: |
          INPUT=$(cat envs/${{ github.event.inputs.environment }}.json)
          echo $INPUT
          echo "::set-output name=INPUT_JSON::$INPUT"

  MAIN: 
   uses: ./.github/workflows/reuse-json-input.yml
   needs: INPUT
   with:
    INPUT_JSON: ${{ needs.INPUT.outputs.INPUT_JSON }} 
