name: Reuse (JSON Inputs)

on:
  workflow_call:
    inputs:
      INPUT_JSON:
        type: string
        required: true

jobs:
  MAIN: 
   runs-on: ubuntu-latest
   strategy:
      matrix: 
        input: ${{fromJSON(inputs.INPUT_JSON)}}
   steps:
      - id: CHECKOUT
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - id: ENV
        run: |
          for s in $(echo '${{ matrix.input }}' | jq -r "to_entries|map(\"ENV_\(.key|ascii_upcase)=\(.value|tostring)\")|.[]" ); do
            echo $s
            echo $s >> $GITHUB_ENV
          done

      - id: ECHO
        run: |
          cat <<- EOM
          {
            "environment: [{
               "name": "HARDCODED_VARIABLE",
               "value": "hardcoded"
            }, {
               "name": "SOME_VARIABLE",
               "value": "$ENV_SOME_VARIABLE"
            }, {
               "name": "ANOTHER_VARIABLE",
               "value": "$ENV_ANOTHER_VARIABLE"
            }]
          }
          EOM
          
